// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    aws_app_analytics : '',
    aws_cognito_identity_pool_id : '',
    aws_cognito_region : '',
    aws_content_delivery : '',
    aws_content_delivery_bucket : '',
    aws_content_delivery_bucket_region : '',
    aws_content_delivery_cloudfront : '',
    aws_content_delivery_cloudfront_domain : '',
    aws_mobile_analytics_app_id : '',
    aws_project_id : '',
    aws_project_name : '',
    aws_project_region : '',
    aws_resource_name_prefix : '',
    }
    
    export default awsmobile;
    var AWS = require('aws-sdk');
    AWS.config.region = awsmobile.aws_project_region;
    AWS.config.update({customUserAgent: 'MobileHub v0.1'});